name: NottGGWave
version: 1.0.0
main: com.nottabaker.nottggwave.NottGGWave
author: nottabaker
api-version: 1.20
website: https://github.com/nottabaker
description: Plugin para gestionar GG Waves con recompensas personalizables

commands:
  nottggwave:
    description: Comando principal para gestionar GG Waves
    usage: /<command> start
    permission: nottggwave.admin
    aliases: [ggwave, ggw]

permissions:
  nottggwave.admin:
    description: Permiso para administrar GG Waves
    default: op
  nottggwave.use:
    description: Permiso para participar en GG Waves
    default: true

depend: []
softdepend: []
